image: image
surtitle: text_short
title:
  _type: text
  _label: Titre
  _help: Encadrer du texte entre &lt; et &gt; pour le mettre en forme, par exemple &lt; mon texte en italique &gt;. Pour faire des sauts de ligne faire shift+entrer.
push_cta_title: text_short
cta: !load components/cta
cta_contact: !load components/cta
