image: image
title: text_short
subtitle: text_short
text: wysiwyg
cta: !load components/cta
insights:
  _type: repeater
  _repeat:
    title: wysiwyg
    details: text_short
    content: wysiwyg
  _times: 4
