title: text_short
description: wysiwyg
cta: !components cta
cards:
  type: repeater
  repeat:
    image: image
    picto: picto
    title: text_short
    subtitle: text_short
    content: wysiwyg
    cta: !components cta
  times: 6  #repeat n times